language: ruby

git:
  depth: 1

services:
  - docker

script:
  - docker build -t $DOCKER_PRIVATE_REGISTRY/fuck-off-html-page .

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

after_deploy:
  - bash docker-push.sh
