language: node_js

node_js:
  - "10"

services:
  - docker

before_install:
  - docker build -t $DOCKER_PRIVATE_REGISTRY/fuck-off-html-page .

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
