language: ruby

git:
  depth: 1

services:
  - docker

script:
  - docker build -t $DOCKER_PRIVATE_REGISTRY/fuck-off-html-page .

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

after_deploy:
  - 'curl -u "${DEPLOY_BASEAUTH_USER}:${DEPLOY_BASEAUTH_PASSWORD}" -X POST "http://${DEPLOY_TRIGGER_URL}"'
